services:
  frontend:
    build: 
      context: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:8080"
    develop:
      watch:
         - action: sync
           path: ./src
           target: /app/src
         - action: rebuild
           path: package.json
    command: ["yarn", "dev"]
  backend:
    build:
      context: ./backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0  # Ensure FLASK_RUN_HOST is set if using 'flask run' command
      - FLASK_RUN_PORT=5000